In [8]:
import numpy as np


In [11]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [19]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
arrray4 = np.arange(12)

In [26]:
array4 = np.arange(12.)
array4


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [27]:
type(array4)

numpy.ndarray

In [28]:
array4.dtype

dtype('float64')

In [29]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [30]:
vetor1[3]

3

In [31]:
vetor1[0:2]

array([0, 1])

In [32]:
print(vetor1[0:2])

[0 1]


In [36]:
s = np.array(['Python', 'Profissional', 'Java', "Água"])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [37]:
s = np.array(['Python', 16426715378, 'Profissional', 'Java', "Água"])
s

array(['Python', '16426715378', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [38]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [40]:
vetor1[0] = 'Novo Elemento'
vetor1

ValueError: ignored

In [41]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])